name: Streams of Consciousness
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05767
title: Streams of Consciousness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59622046-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#361702'
    - '#534926'
    - '#775f3c'
    - '#c29345'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
