name: Streams of Consciousness
favicon: null
layout_spectrum: 0.6216777877416462
typography_spectrum: 0.7925913033541292
title: Streams of Consciousness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59622046-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3392c'
    - '#e4f6f8'
    - '#434262'
    - '#c0777e'
    - '#c3a4bc'
  brandStrength: 0.5196880623698235
  lightness: 0.11764859850518405
  saturation: 0.2870909362100065
  rhythmicContrast: 0.06417260435409844
purpose: []
