name: Streams of Consciousness
favicon: null
layout_spectrum: 0.6216777877416462
typography_spectrum: 0.7925913033541292
title: Streams of Consciousness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59622046-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#021138'
    - '#562b46'
    - '#616d5f'
    - '#294747'
    - '#16323d'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
