name: Streams of Consciousness
favicon: null
layout_spectrum: 0.6216777877416462
typography_spectrum: 0.7925913033541292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5196880623698235
  lightness: 0.11764859850518405
  saturation: 0.2870909362100065
  rhythmicContrast: 0.06417260435409844
purpose: []
